TaskProekt/Entities/Task.cs
using System.ComponentModel.DataAnnotations;

namespace TaskProekt.Entities;

public class Task
{
	public int Id { get; set; }
	[Required(ErrorMessage = "Title is required")]
	public string Title { get; set; }
	public string Description { get; set; }
	[DataType(DataType.Date)]
	public DateTime DueDate { get; set; }
	public EStatus Status { get; set; }
}

TaskProekt/Controllers/AuditViewController.cs
using Microsoft.AspNetCore.Mvc;
using TaskProekt.Services.Interfaces;

namespace TaskProekt.Controllers;

public class AuditViewController : Controller
{
    readonly IAuditRepository _context;
    public AuditViewController(IAuditRepository context) => _context = context;
    public async Task<IActionResult> Index(DateTime? fromDate, DateTime? toDate, string Name)
        => View(await _context.Index(fromDate, toDate, Name));
}

TaskProekt/Controllers/TaskController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NToastNotify;
using TaskProekt.Data;
using TaskProekt.Entities;
using TaskProekt.Services.Interfaces;
using Task = TaskProekt.Entities.Task;
namespace TaskProekt.Controllers;

public class TaskController : Controller
{
    private readonly ITaskRepository _taskRepository;
    private readonly UserManager<User> _userManager;
    private readonly IToastNotification _toastNotification;
    private readonly AppDbContext _appDbContext;
    public TaskController(ITaskRepository productRepository, UserManager<User> userManager, IToastNotification toastNotification, AppDbContext appDbContext)
    {
        _taskRepository = productRepository;
        _userManager = userManager;
        _toastNotification = toastNotification;
        _appDbContext = appDbContext;
    }
    public async Task<IActionResult> Index()
    {
        var tasks = await _taskRepository.GetAllTasksAsync();

        var productViewModels = tasks.Select(p => new Task()
        {
            Id = p.Id,
            Title = p.Title,
            Description = p.Description,
            DueDate = p.DueDate,
            Status = p.Status,
        }).ToList();

        return View(productViewModels);
    }
    [Authorize(Roles = "ADMIN")]
    public async Task<IActionResult> Details(int id)
    {
        try
        {
            if (id == null) return NotFound();
            var task = await _taskRepository.GetTaskByIdAsync(id);
            if (task == null) return NotFound();
            _toastNotification.AddSuccessToastMessage("Detail Found");
            return View(task);
        }
        catch (Exception ex)
        {
            _toastNotification.AddErrorToastMessage("Detail not found");
            return RedirectToAction("Index", "Home");
        }
    }
    [Authorize(Roles = "ADMIN,MANAGER")]
    public IActionResult Create() => View();
    [Authorize(Roles = "ADMIN,MANAGER")]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,Title,Description,DueDate,Status,Email")] Task task, string email)
    {
        if (!ModelState.IsValid)
        {
            return View(task);
        }
        task.DueDate = DateTime.SpecifyKind(task.DueDate, DateTimeKind.Utc);

        DateTime Limetdate = new DateTime(2050, 1, 1);
        var oldtime = DateTime.UtcNow;
        if (task.DueDate < Limetdate && task.DueDate < oldtime)
        {
            ModelState.AddModelError("", "date is incorrect");
            return View(task);
        }
        var user = await _userManager.GetUserAsync(HttpContext.User);
        await _taskRepository.CreateTaskAsync(task, email);
        await _taskRepository.CreateAudit(task, null, "Create", user);
        _toastNotification.AddSuccessToastMessage("Created successfully");
        return RedirectToAction(nameof(Index));
    }
    [Authorize(Roles = "ADMIN")]
    public async Task<IActionResult> Edit(int id)
    {
        try
        {
            if (id == null) return NotFound();
            var task = await _taskRepository.GetTaskByIdAsync(id);
            if (task == null) return NotFound();
            return View(task);
        }
        catch (Exception ex)
        {
            return RedirectToAction("Index", "Home");
        }
    }
    [HttpPost]
    [Authorize(Roles = "ADMIN")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,DueDate,Status")] Task task)
    {
        if (id != task.Id) return NotFound();
        if (!ModelState.IsValid)
        {
            _toastNotification.AddErrorToastMessage("Bu yerda Items yoq.Please try again");
            return View(task);
        }
        try
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var oldTask = await _taskRepository.GetOldValueAsync(id);
            var newTask = await _taskRepository.UpdateTaskAsync(task);
            await _taskRepository.CreateAudit(newTask, oldTask, "Edit", user);
        }
        catch (DbUpdateConcurrencyException)
        {
            if (_taskRepository.GetTaskByIdAsync(task.Id) == null) return NotFound();
            else
                throw;

        }
        _toastNotification.AddSuccessToastMessage("task change successfully");
        return RedirectToAction(nameof(Index));
    }
    public IActionResult Delete() => View();
    [Authorize(Roles = "ADMIN")]
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int id)
    {
        if (!ModelState.IsValid)
            return View("Index");
        var task = await _taskRepository.DeleteTaskAsync(id);
        if (task == null) return NotFound();

        var user = await _userManager.GetUserAsync(HttpContext.User);
        await _taskRepository.CreateAudit(task, null, "Detele", user);
        _toastNotification.AddSuccessToastMessage("Your task deleted");
        return RedirectToAction(nameof(Index));
    }
    [Authorize(Roles = "ADMIN")]
    public IActionResult CreateTaskForUser()
    {
        return View();
    }
}

TaskProekt/Views/Task/Create.cshtml
@model TaskProekt.Entities.Task
@{
    ViewData["Title"] = "Create";
}
<h1>Create</h1>
<body>
    <div class=" col-md-4">
        <form asp-controller="Task" asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="Email">Email</label>
                <input type="email" id="Email" name="Email" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="DueDate" class="control-label"></label>
                <input asp-for="DueDate" class="form-control" type="date" />
                <span asp-validation-for="DueDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" class="form-control">
                    <option value=""> Select status</option>
                    <option value="0"> Created </option>
                    <option value="1">In Progress</option>
                    <option value="2"> Completed </option>
                </select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary my-2" />
            </div>
        </form>
    </div>
</body>

TaskProekt/Views/Task/Delete.cshtml
@model TaskProekt.Entities.Task
@{
	ViewData["Title"] = "Delete";
}
<h1>Delete</h1>
<body>
	<form asp-controller="Task" asp-action="Delete" method="post" enctype="multipart/form-data" class="col-md-6" style="margin: 5px auto;">
		<div class="login-box">
			<h1>Task</h1>
			<div class="textbox>
				<i class="fa fa-user" aria-hidden="true"></i>
				<input asp-for="Id" type="number" id="form1-Admin" placeholder="Id">
			</div>
			<button asp-controller="Task" asp-action="Delete" type="submit" class="btn btn-pill btn-outline-info" style="width: 100%;">
				<i class="fa fa-sign-in mr-1"></i> Delete
			</button>
		</div>
	</form>
</body>

TaskProekt/Views/Task/Edit.cshtml
@model TaskProekt.Entities.Task
@{
	ViewData["Title"] = "Edit";
}
<h1>Edit</h1>
<h4>Product</h4>
<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="Edit">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<input type="hidden" asp-for="Id" />
			<div class="form-group">
				<label asp-for="Title" class="control-label"></label>
				<input asp-for="Title" class="form-control" />
				<span asp-validation-for="Title" class=" text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Description" class="control-label"></label>
				<input asp-for="Description" class="form-control" />
				<span asp-validation-for="Description" class=" text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="DueDate" class="control-label"></label>
				<input asp-for="DueDate" class="form-control" />
				<span asp-validation-for="DueDate" class=" text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Status" class="control-label"></label>
				<input asp-for="Status" class="form-control" />
				<span asp-validation-for="Status" class=" text-danger"></span>
			</div>
			<div class="form-group">
				<input type="submit" value="Save" class="btn btn-primary my-2" />
			</div>
		</form>
	</div>
</div>
<div>
	<a asp-action="Index">Back to List</a>
</div>
@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}

TaskProekt/Views/Task/Index.cshtml
@using TaskProekt.Entities
@model IEnumerable<TaskProekt.Entities.Task>

<h1>Products</h1>
@if (User.Identity != null && User.Identity.IsAuthenticated && User.IsInRole("ADMIN"))
{

    <a asp-action="Create" class="btn btn-primary">Create New</a>
    <button class="btn btn-dark" onclick="location.pathname = '@Url.Action("Index", "AuditView")'">View Audit</button>
    <button class="btn btn-dark" onclick="location.pathname = '@Url.Action("CreateUser", "Account")'">Create User</button>
    <button class="btn btn-dark" onclick="location.pathname = '@Url.Action("Create", "Task")'">Create Task</button>
    <button class="btn btn-info" onclick="location.pathname = 'swagger'">Swagger</button>
}
@if (User.Identity != null && User.Identity.IsAuthenticated && User.IsInRole("MANAGER"))
{
    <a asp-action="Create" class="btn btn-primary">Create New</a>

}
<table class="table  table-bordered table-hover my-2">
    <thead class="thead-dark">
        <tr>

            <th scope="col">
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.DueDate)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Status)
            </th>
            @if (User.Identity != null && User.Identity.IsAuthenticated && User.IsInRole("ADMIN"))
            {
                <th></th>
            }
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DueDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                @if (User.Identity != null && User.Identity.IsAuthenticated && User.IsInRole("ADMIN"))
                {
                    <td style="display:flex; justify-content:center; align-items:center; gap:5px;">
                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-info">Edit</a> <span>|</span>
                        <form asp-controller="TaskModel " asp-action="Delete" method="post">
                            <div>
                                <input name="Id" asp-for="@item.Id" type="hidden" id="form1-Admin" placeholder="Id">
                                <button asp-action="Delete" type="submit" class="btn btn-pill btn-danger">
                                    Delete
                                </button>
                            </div>
                        </form>
                    </td>
                }
            </tr>
        }
    </tbody>
</table>